/**
 * Template config file to be used by mongolux.bootstrap() function.
 * You can copy this file and overwrite values as needed. 
 * 
 * All except uri and db are present in the Mongodb node.js driver documentation.
 * Visit http://mongodb.github.io/node-mongodb-native/3.1/reference/connecting/connection-settings/
 * for more details.
 * 
 */

module.exports = {
  database1: {
    uri: 'mongodb://127.0.0.1:4000/?retryWrites=true',
    db: 'db1',
    useNewUrlParser: true,
    poolSize: 5,
    ssl: false,
    sslValidate: true,
    sslCA: null,
    sslCert: null,
    sslKey: null,
    sslPass: null,
    autoReconnect: true,
    noDelay: true,
    keepAlive: 30000,
    connectTimeoutMS: 30000,
    socketTimeoutMS: 360000,
    reconnectTries: 30,
    reconnectInterval: 1000,
    ha: true,
    haInterval: 10000,
    replicaSet: null,
    secondaryAcceptableLatencyMS: 15,
    acceptableLatencyMS: 15,
    connectWithNoPrimary: false,
    authSource: null,
    w: null,
    wtimeout: null,
    j: false,
    forceServerObjectId: false,
    serializeFunctions: false,
    ignoreUndefined: false,
    raw: false,
    promoteLongs: true,
    promoteBuffers: false,
    promoteValues: true,
    domainsEnabled: false,
    bufferMaxEntries: -1,
    readPreference: null,
    pkFactory: null,
    promiseLibrary: null,
    readConcern: null,
    maxStalenessSeconds: null,
    appname: null,
    loggerLevel: null,
    logger: null,
  },
  database2: {
    uri: 'mongodb://127.0.0.1:4001/?retryWrites=true',
    db: 'db2',
    useNewUrlParser: true,
    poolSize: 5,
    ssl: false,
    sslValidate: true,
    sslCA: null,
    sslCert: null,
    sslKey: null,
    sslPass: null,
    autoReconnect: true,
    noDelay: true,
    keepAlive: 30000,
    connectTimeoutMS: 30000,
    socketTimeoutMS: 360000,
    reconnectTries: 30,
    reconnectInterval: 1000,
    ha: true,
    haInterval: 10000,
    replicaSet: null,
    secondaryAcceptableLatencyMS: 15,
    acceptableLatencyMS: 15,
    connectWithNoPrimary: false,
    authSource: null,
    w: null,
    wtimeout: null,
    j: false,
    forceServerObjectId: false,
    serializeFunctions: false,
    ignoreUndefined: false,
    raw: false,
    promoteLongs: true,
    promoteBuffers: false,
    promoteValues: true,
    domainsEnabled: false,
    bufferMaxEntries: -1,
    readPreference: null,
    pkFactory: null,
    promiseLibrary: null,
    readConcern: null,
    maxStalenessSeconds: null,
    appname: null,
    loggerLevel: null,
    logger: null,
  },
}
